FROM golang:alpine as dev
WORKDIR $GOPATH/src/keva/node/
COPY . .
RUN CGO_ENABLED=0 go build -o /go/bin/node cmd/node/main.go

FROM scratch
COPY --from=dev /go/bin/node /go/bin/node
ENTRYPOINT [ "/go/bin/node"]
