FROM golang:alpine as dev
WORKDIR $GOPATH/src/keva/gateway/
COPY . .
RUN CGO_ENABLED=0 go build -o /go/bin/gateway cmd/gateway/main.go

FROM scratch
COPY --from=dev /go/bin/gateway /go/bin/gateway
ENV PORT=5555
EXPOSE  5555
ENTRYPOINT [ "/go/bin/gateway"]
